quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-orm.database.generation=create

# CORS configuration
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with